# Ansible inventory generated by Terraform

all:
  hosts:
    ${instance_name}:
      ansible_host: ${instance_ip}

  vars:
    http_port: 80
    ansible_user: ec2-user
    # Path relative to ansible playbook
    ansible_ssh_private_key_file: ../iac-terraform/${instance_key}
