version: '3'
services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: monitor-prometheus
    restart: unless-stopped
    ports:
      - 9090:9090 # Comment out for production! Unsafe!
    expose:
      - 9090
    command: 
      - "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ${DATA_FOLDER}/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ${DATA_FOLDER}/prometheus:/prometheus
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter
    user: "${UID}:${GID}"
    
  grafana:
    image: docker.io/grafana/grafana-oss:latest
    container_name: monitor-grafana
    restart: unless-stopped
    ports:
      - 9030:3000
    volumes:
      - ${DATA_FOLDER}/grafana:/var/lib/grafana
    links:
      - prometheus:prometheus
      - loki:loki
    user: "${UID}:${GID}"

  loki:
    image: grafana/loki:latest
    container_name: monitor-loki
    restart: unless-stopped
    volumes:
      - ${DATA_FOLDER}/loki:/etc/loki
    command: "--config.file=/etc/loki/loki-config.yml"
    # ports:
    #   - 3100:3100
    user: "${UID}:${GID}"
    
  promtail:
    image: grafana/promtail:latest
    container_name: monitor-promtail
    volumes:
      - /var/log:/var/log
      - ${DATA_FOLDER}/promtail:/etc/promtail
    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: "--config.file=/etc/promtail/promtail-config.yml"
    links:
      - loki:loki

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitor-node-exporter
    restart: unless-stopped
    expose:
      - 9100

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: monitor-cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080