version: '3'
services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: monitor-prometheus
    restart: unless-stopped
    ports:
      - 9090:9090 # Comment out for production! Unsafe!
    expose:
      - 9090
    command: 
      - "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ${DATA_FOLDER}/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ${DATA_FOLDER}/prometheus:/prometheus
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter
    user: "${UID}:${GID}"
    
  grafana:
    image: docker.io/grafana/grafana-oss:latest
    container_name: monitor-grafana
    restart: unless-stopped
    ports:
      - 9030:3000
    volumes:
      - ${DATA_FOLDER}/grafana:/var/lib/grafana
    links:
      - prometheus:prometheus
    user: "${UID}:${GID}"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitor-node-exporter
    restart: unless-stopped
    expose:
      - 9100

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: monitor-cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080