- name: Ensure the app directory exists
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Copy docker-compose.yml
  copy:
    src: "{{ playbook_dir }}/../docker-compose.yml"
    dest: "{{ app_dir }}/docker-compose.yml"
    owner: ec2-user
    group: ec2-user
    mode: '0644'
  become: yes

- name: Run docker-compose
  command: "docker-compose -f {{ app_dir }}/docker-compose.yml up -d"
  args:
    chdir: "{{ app_dir }}"
  become: yes

- name: Prune old images and containers
  command: "docker system prune -f"
  become: yes
