- name: Install nodejs and npm
  yum:
    name:
      - nodejs
      - npm
    state: present
    update_cache: yes

- name: Copy nodejs app from local repository
  ansible.builtin.synchronize:
    src: "{{ playbook_dir }}/../node_app/"
    dest: "{{ app_dir }}"
    mode: push
    recursive: yes
    owner: yes
    group: yes
    compress: yes
    rsync_opts:
      - "--delete"
      - "--exclude=node_modules"

- name: Install npm dependencies
  npm:
    path: "{{ app_dir }}"

- name: Install PM2 globally using npm
  npm:
    name: pm2
    global: yes
      
- name: Stop nodejs app (if running)
  command: pm2 stop {{ app_dir }}/index.js
  ignore_errors: yes

- name: Start nodejs app
  command: pm2 start {{ app_dir }}/index.js
