- name: Update packages
  yum:
    name: "*"
    state: latest

- name: Install utils
  yum:
    name:
      - vim
      - fail2ban
    state: present
    update_cache: yes

- name: Enable fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: yes