name: Deploy Node.js app to server

on:
  push:
    paths:
      # Trigger only on pushes to the web directory
      - 'nodejs-service-deployment/node_app/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      
      # Step 3: Install Node.js (optional, if your server doesn't have it already)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # or any version you're using

      # Step 4: Install dependencies (optional, if required)
      - name: Install dependencies
        run: npm install

      # Step 5: Rsync the app to the server
      - name: Deploy to server using rsync
        run: |
          rsync -avz --delete ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }}:/opt/app
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
