name: Deploy Node.js app to server

on:
  push:
    paths:
      # Trigger only on pushes to the web directory
      - 'nodejs-service-deployment/node_app/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 400 private_key.pem
          
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          
      - name: Create Ansible inventory
        run: |
            echo "[webservers]" > inventory.ini
            echo "${{ secrets.SSH_IP }} ansible_user=${{ secrets.SSH_USER }} ansible_ssh_private_key_file=private_key.pem" >> inventory.ini
            
      - name: Run playbook
        env:
          ANSIBLE_USER: ${{ secrets.SSH_USER }}
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook -i inventory.ini ./nodejs-service-deployment/ansible/node_setup.yml --tags app
        
