name: Deploy Node.js app to server

on:
  push:
    paths:
      # Trigger only on pushes to the web directory
      - 'nodejs-service-deployment/node_app/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      
      - name: Install dependencies
        run: npm install
        working-directory: ./nodejs-service-deployment/node_app

      - name: rsync deployment
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avz --delete
          path: ./nodejs-service-deployment/node_app
          remote_path: "~/app"
          remote_host: ${{ secrets.SSH_IP }}
          remote_user: ec2-user
          remote_key: ${{ secrets.DEPLOY_KEY }}
          
      - name: Run PM2 stop command
        run: |
          ssh ec2-user@${{ secrets.SSH_IP }} "pm2 stop all"
          
      - name: Run PM2 start command
        run: |
          ssh ec2-user@${{ secrets.SSH_IP }} "cd ~/app && pm2 start index.js --name 'app'"
