name: Deploy Node.js app to server

on:
  push:
    paths:
      # Trigger only on pushes to the web directory
      - 'nodejs-service-deployment/node_app/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      
      - name: Install dependencies
        run: npm install

      - name: Deploy to server using rsync
        run: |
          rsync -avz --delete ./ ec2-user@${{ secrets.SSH_IP }}:~/app
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      
      - name: Run PM2 stop command
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.SSH_IP }} "pm2 stop all"
          
      - name: Run PM2 start command
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.SSH_IP }} "cd ~/app && pm2 start index.js --name 'app'"
